-- 2010-07-15
USE SHIPS

-- 2.1 В)
SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS < 6 AND COUNTRY IN (SELECT COUNTRY
                                  FROM CLASSES
                                  WHERE NUMGUBNS < 6);

-- 2.2. Г)
SELECT COUNTRY, COUNT(DISTINCT BATTLE) AS NUM_BATTLES
FROM OUTCOMES
JOIN SHIPS ON NAME = SHIP
RIGHT JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY COUNTRY
HAVING COUNT(DISTINCT BATTLE) <= 2;