-- 2019-07-09, 4
USE Movies;

-- 4.1. A)
SELECT S.NAME, COUNT(M.TITLE) as CNT
FROM STUDIO S JOIN MOVIE M 
ON S.NAME = M.STUDIONAME
GROUP BY S.NAME
HAVING CNT < 2;

-- 4.2. version-1 
SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH = (	SELECT NETWORTH
FROM MOVIEEXEC
ORDER BY NETWORTH ASC LIMIT 1);

-- 4.2. version-2 
SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH <= ALL(	SELECT NETWORTH
FROM MOVIEEXEC
WHERE NETWORTH IS NOT NULL);

-- 4.2. version-3 
SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH IN (	SELECT MIN(NETWORTH)
FROM MOVIEEXEC);