-- 2019-09-10, 4
USE Movies;

-- 4.1. Б)
SELECT ME.NAME, M.YEAR, COUNT(*) AS CNT
FROM MOVIEEXEC ME
JOIN MOVIE M
ON ME.CERT# = M.PRODUCERC#
GROUP BY ME.CERT#, ME.NAME, M.YEAR

-- 4.2. version-1 
SELECT NAME 
FROM MOVIESTAR
WHERE BIRTHDATE >= (SELECT BIRTHDATE
FROM MOVIESTAR
ORDER BY BIRTHDATE DESC LIMIT 1);

-- 4.2. version-2 
SELECT name
FROM MOVIESTAR
WHERE BIRTHDATE >= ALL(	SELECT BIRTHDATE
FROM MOVIESTAR
WHERE BIRTHDATE IS NOT NULL);
-- 4.3. version-3 
SELECT name
FROM MOVIESTAR 
WHERE BIRTHDATE IN (SELECT MAX(BIRTHDATE)
FROM MOVIESTAR);
