-- 2.1 в)
SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS < 6 AND COUNTRY IN (SELECT NCOYNTRY
                                  FROM CLASSES
                                  WHERE NUMGUBNS < 6);

-- 2.2. г)
SELECT COUNTRY, COUNT(DISTINCT BATTLE) AS NUM_BATTLES
FROM OUTCOMES
JOIN SHIPS ON NAME = SHIP
RIGHT JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY COUNTRY
HAVING COUNT(DISTINCT BATTLE) <= 2;